name: Update IPTV

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次
  workflow_dispatch:       # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update.py

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add IPTV.m3u
          git commit -m "Auto update IPTV.m3u" || echo "No changes"
          git push
